dreamer/urls.py
from django.contrib import admin
from django.urls import path, include

#Для обработки выгруженных файлов
from django.conf import settings
from django.conf.urls.static import static

app_name = 'dreamer'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
]


if settings.DEBUG: #Этот путь нужен только если сайт работает в отладочном режиме
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

main/urls.py
from django.contrib import admin
from django.urls import path

from .views import homepage, index, blog_detail, create_blog, delete_blog, searchinput, by_category, search, registerview, subscribe_blog, unsubscribe_blog, my_subscribes, profile, biography_edit, email_edit, contact, comment_delete

from django.contrib.auth.views import LoginView, LogoutView

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('homepage/', homepage, name='homepage'),
    path('by_category/<str:category>', by_category, name='by_category'),
    path('email/<str:aid>/', email_edit, name = 'email_edit'),
    path('contact/<str:contact_user>/', contact, name = 'contact'),
    path('biography_edit/<str:aid>/', biography_edit, name = 'bioedit'),
    path('profile/<str:aid>/', profile, name = 'profile'),
    path('detail/<str:blog_id>/<str:comment_id>', comment_delete, name = 'comment_delete'),
    path('detail/<int:author_id>/subscribe/', subscribe_blog, name = 'subscribe'),
    path('detail/<int:author_id>/unsubscribe/', unsubscribe_blog, name = 'unsubscribe'),
    path('my_subscribes/', my_subscribes, name='my_subscribes'),
    path('register/', registerview, name = 'register'),
    path('add/', create_blog, name = 'add'),
    path('delete/<int:blog_id>/', delete_blog, name = 'delete'),
    path('searchuser/', searchinput, name = 'searchinput'),
    path('search/<str:search>/', search, name = 'search'),
    path('detail/<int:blog_id>/', blog_detail, name = 'detail'),
    path('accounts/login/', LoginView.as_view(redirect_field_name='main:add', template_name="main/login_website.html"), name = 'login'),
    path('accounts/logout/', LogoutView.as_view(next_page='main:homepage', template_name = "logged_out_website.html"), name = 'logout'),
]

main/forms.py
from django import forms
from .models import Blog, Search, Person, Biography, Email, DreamRubric, Comment

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.core.validators import FileExtensionValidator


class BlogForm(forms.ModelForm):
    title = forms.CharField(label = 'Header')
    text = forms.CharField(label = 'Text')
    image = forms.ImageField(label = 'Image', validators = [FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], error_messages={'invalid_extension': 'This format is not supported.'}, required = False)
    
    class Meta:
        model = Blog
        fields = ('title', 'text', 'image',)
        
        
class CommentForm(forms.ModelForm):
    comment_text = forms.CharField(label = '', widget=forms.widgets.Textarea())
    
    class Meta:
        model = Comment
        fields = ('comment_text',)
        

class SearchForm(forms.ModelForm):
    search_field = forms.CharField(label = '', required = False)
    
    class Meta:
        model = Search
        fields = ('search_field',) 
        
        
class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter your username', min_length=4, max_length=150)
    password1 = forms.CharField(label='Enter your password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm your password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Nickname already taken")
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password mismatch")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['password1']
        )
        return user
    
        
        
class BiographyForm(forms.ModelForm):
    bio = forms.CharField(label = "Describe yourself", error_messages={'required': 'About'}, widget=forms.widgets.Textarea())
    dream = forms.CharField(label = "Dream", error_messages={'required': 'Your dream'})
    dreamrubric = forms.ModelChoiceField(queryset = DreamRubric.objects.all(), label = "Category", empty_label = None, error_messages={'required': 'Choose category'}, widget=forms.widgets.Select(attrs={'size': 8}))
    #Походу надо всетаки создать модель dreamrubric и связать её 
    
    class Meta:
        model = Biography
        fields = ('bio', 'dream', 'dreamrubric',)
        
        
class EmailForm(forms.ModelForm):
    email = forms.EmailField(label = "", error_messages={'required': 'Enter your Email'})
    
    class Meta:
        model = Email
        fields = ('email',)

main/views.py
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.models import User, UserManager

from django.contrib.auth.views import redirect_to_login

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.http import HttpResponseRedirect

from django.urls import reverse

from .forms import BlogForm, SearchForm, BiographyForm, EmailForm, CommentForm, CustomUserCreationForm

from django.contrib.auth.forms import UserCreationForm


from .models import Blog, Person, DreamRubric, Biography, Comment

from django.core.mail import send_mail

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        if request.user.person.dream != '' or request.user.person.biography != 'Hello. I have not chosen my dream yet.':
            request.user.person.stringid = request.user.id
            request.user.save()
            return HttpResponseRedirect(reverse('main:homepage', args=()))
        else:
            request.user.person.stringid = request.user.id
            request.user.save()
            return HttpResponseRedirect(reverse('main:bioedit', args=(request.user.id,)))
    else:
        return HttpResponseRedirect(reverse('main:login', args = ()))
    
def homepage(request):
    if request.user.is_authenticated:
        best_category = 0
        best_category_name = 'Отсутствует'
        
        #Сейчас сначала выводятся пользователи любимой категории, а потом уже все остальные. То есть, если у пользователя 0 подписчиков, но он в любимой категории, он будет выводится выше пользователя, у которого больше подписчиков, но не любимая категория.
        #Кстати, циклы в views работают
    
        if best_category < request.user.person.tourism_views:
            best_category = request.user.person.tourism_views
            best_category_name = 'Tourism'
    
        if best_category < request.user.person.travel_views:
            best_category = request.user.person.travel_views
            best_category_name = 'Travel'
    
        if best_category < request.user.person.technologies_views:
            best_category = request.user.person.technologies_views
            best_category_name = 'Technologies'
        
        if best_category < request.user.person.car_views:
            best_category = request.user.person.car_views
            best_category_name = 'Vehicle'

        if best_category < request.user.person.food_views:
            best_category = request.user.person.food_views
            best_category_name = 'Food'

        if best_category < request.user.person.collecting_views:
            best_category = request.user.person.collecting_views
            best_category_name = 'Collecting'

        if best_category < request.user.person.career_views:
            best_category = request.user.person.career_views
            best_category_name = 'Career'

        if best_category < request.user.person.health_views:
            best_category = request.user.person.health_views
            best_category_name = 'Health'

        if best_category < request.user.person.meeting_views:
            best_category = request.user.person.meeting_views
            best_category_name = 'Communication'

        if best_category < request.user.person.other_views:
            best_category = request.user.person.other_views
            best_category_name = 'Other'
        
        best_person = Person.objects.filter(rubric = best_category_name).order_by('-subscribes')   
        person = Person.objects.exclude(rubric = best_category_name).order_by('-subscribes')
        rubrics = DreamRubric.objects.all()
    
        context = {'best_person' : best_person, 'person' : person, 'rubrics' : rubrics}
        return render(request, 'main/index.html', context)
    
    else:
        person = Person.objects.order_by('-subscribes')
        rubrics = DreamRubric.objects.all()
        
        context = {'person' : person, 'rubrics' : rubrics}
        return render(request, 'main/index.html', context)
    
    
def by_category(request, category):
    person = Person.objects.filter(rubric = category).order_by('-subscribes')
    rubrics = DreamRubric.objects.all()
    
    context = {'person' : person, 'rubrics' : rubrics}
    return render(request, 'main/by_category.html', context)
    
    
def searchinput(request):
    if request.user.is_authenticated:
        rubrics = DreamRubric.objects.all()
        if request.method == 'POST':
            srch = SearchForm(request.POST)
            if srch.is_valid():
                srch = srch.save(commit=False)
                search = srch.search_field
                srch.save()
                return HttpResponseRedirect(reverse('main:search', args=(search,)))
            else:
                context = {'form' : srch, 'rubrics' : rubrics}
                return render(request, 'main/searchinput.html', context)
        else:
            srch = SearchForm(request.POST)
            return render(request, 'main/searchinput.html', {'form' : srch, 'rubrics' : rubrics})
    else:
        return HttpResponseRedirect(reverse('main:login', args = ()))
    
    
def search(request, search):
    persons = User.objects.filter(username__icontains = search).order_by('id')
    rubrics = DreamRubric.objects.all()
    context = {'persons' : persons, 'rubrics' : rubrics}
    return render(request, 'main/personsearch.html', context)
    
def blog_detail(request, blog_id):
    blog = Blog.objects.get(pk = blog_id)
    comment = Comment.objects.filter(comment_blogid = blog_id)
    comment_id = get_object_or_404(Blog, id = blog_id)
    rubrics = DreamRubric.objects.all()
    if str(request.user.id) not in blog.viewers:
        blog.views += 1
        blog.viewers += ' '
        blog.viewers += str(request.user.id)
        blog.save()
        
    if request.method == 'POST':
        cmn = CommentForm(request.POST)
        if cmn.is_valid():
            cmn = cmn.save(commit=False)
            cmn.comment_author = request.user.username
            cmn.publicationcomment = comment_id
            cmn.comment_authorid = request.user.id
            cmn.comment_blogid = blog.id
            cmn.save()
            return HttpResponseRedirect(reverse('main:detail', args=(blog_id,)))
        else:
            context = {'blog' : blog, 'comment' : comment, 'comment_id' : comment_id, 'form' : cmn, 'rubrics' : rubrics}
            return render(request, 'main/detail.html', context)
    else:
        cmn = CommentForm()
        context = {'blog' : blog, 'comment' : comment, 'comment_id' : comment_id, 'form' : cmn, 'rubrics' : rubrics}
        return render(request, 'main/detail.html', context)
    
    
def comment_delete(request, blog_id, comment_id):
    comment = Comment.objects.get(id = comment_id)
    if request.user.username == comment.comment_author or request.user.is_staff:
        comment.delete()
    return HttpResponseRedirect(reverse('main:detail', args=(blog_id,)))

    
def contact(request, contact_user):
    if request.user.is_authenticated:
        if request.user.person.email != '':
            user = User.objects.get(id = contact_user)
            message = f'Hello, {user.username}! User {request.user.username} wants to contact you. You can reply to this mail: {request.user.person.email}.'
            send_mail('Dreamer', message, 'morethanicloud@icloud.com', [user.person.email], fail_silently=False)
            return HttpResponseRedirect(reverse('main:profile', args = (contact_user,)))
        else:
            return HttpResponseRedirect(reverse('main:email_edit', args = (request.user.id,)))
    else:
        return HttpResponseRedirect(reverse('main:login', args = ()))

def create_blog(request):
    if request.user.is_authenticated:
        rubrics = DreamRubric.objects.all()
        if request.method == 'POST':
            bf = BlogForm(request.POST, request.FILES)
            if bf.is_valid():
                bf = bf.save(commit=False)
                bf.author = request.user.username
                bf.tauthor = Person.objects.get(id = request.user.id)
                bf.authorid = request.user.id
                bf.save()
                return HttpResponseRedirect(reverse('main:profile', args=(request.user.id,)))
            else:
                return render(request, 'main/create.html', {'form' : bf, 'rubrics' : rubrics})
        else:
            bf = BlogForm()
            return render(request, 'main/create.html', {'form' : bf, 'rubrics' : rubrics})
    else:
        return HttpResponseRedirect(reverse('main:login', args = ()))

def delete_blog(request, blog_id):
    blog = Blog.objects.get(pk = blog_id)
    if request.user.is_authenticated and request.user.username == blog.author:
        blog.image.delete()
        blog.delete()
        return HttpResponseRedirect(reverse('main:profile', args=(blog.authorid,)))
    else:
        return HttpResponseRedirect(reverse('main:detail', args=(blog_id,)))
    
def subscribe_blog(request, author_id):
    if request.user.is_authenticated:
        author = get_object_or_404(User, id = author_id)
        if str(author.id) in request.user.person.subscribed:
            context = {'author' : author}
            return HttpResponseRedirect(reverse('main:profile', args=(author.id,)))
        else:
            author.person.subscribes += 1 
            request.user.person.subscribed += ' '
            request.user.person.subscribed += str(author.id)
            author.person.save()
            request.user.save()
            if author.person.email != '':
                send_mail('ComeTrue', 'You have a new subscriber!', 'morethanicloud@icloud.com', [author.person.email], fail_silently=False)
            context = {'author' : author}
            return HttpResponseRedirect(reverse('main:profile', args=(author.id,)))
    else:

main/templates/main/base.html
<!DOCTYPE html>

{% load thumbnail %}
{% load static %}

<html>
<head>
    <title>Come True</title>
    <meta charset="UTF-8">
    <!-- <link rel="stylesheet" href="{% static 'css/indexcss.css' %}">  -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</head>
    
<body>
    <!-- HEADER -->
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
              
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">Come True</h4>
              <p class="text-muted">Make your dreams come true! –(c) Shia LaBeouf</p>
            </div>
              
            <div class="col-sm-8 col-md-7 py-4">
                <h4 class="text-white">Categories:
                {% for rubric in rubrics %} 
                {% if forloop.last %}
                <a href="{% url 'main:by_category' category=rubric.drubric %}" class="text-white">{{ rubric.drubric }}.</a>
                  
                {% else %} 
                <a href="{% url 'main:by_category' category=rubric.drubric %}" class="text-white">{{ rubric.drubric }},</a>
                  
                {% endif %}
                {% endfor %}
                </h4>
            </div>
              
            {% if request.user.is_authenticated %}
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Navigation:</h4>
              <ul class="list-unstyled">
                <li><a href="{% url 'main:homepage' %}">Homepage</a></li>
                <li><a href="{% url 'main:my_subscribes' %}">My subscribes</a></li>
                <li><a href="{% url 'main:profile' aid=request.user.id %}">Profile</a></li>
                <li><a href="{% url 'main:searchinput' %}">Search</a></li>
                <li><a href="{% url 'main:logout' %}">Quit</a></li>
                  
                {% if request.user.client.status == 'Admin' or request.user.client.status == 'Moderator' %}
                <li><a href="{% url 'main:article_publish' %}">Add article</a></li>
                  
                {% if request.user.client.status == 'Admin' %}
                <li><a href="{% url 'main:moderating_bio_all' %}">Profile moderation</a></li>
                {% endif %}
                {% endif %}  
                  
                
              </ul>
            </div>
            {% else %}
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Navigation:</h4>
              <ul class="list-unstyled">
                <li><a href="{% url 'main:register' %}">Register</a></li>
                <li><a href="{% url 'main:login' %}">Log in</a></li>
              </ul>
            </div>
            {% endif %} 
          </div>
        </div>
      </div>
        
        
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'main:homepage' %}" class="navbar-brand d-flex align-items-center">
            <strong>Come True</strong>
          </a>
          <h2 class="navbar-brand d-flex align-items-center">{% if request.user.is_authenticated %} Hello, {{request.user.username}}! {% endif %}</h2>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    
    {% block content %}
    {% endblock %}
    
    <!-- FOOTER -->
    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
            <a href="#"></a>
            </p>
            <p>All rights reserved by &copy; ComeTrue, 2021</p>
        </div>
    </footer>
</body>
</html>

main/templates/main/biography_edit.html
{% extends "main/base.html" %}
{% block content %}
    
    
    <!-- CHANGING_BIO  -->
    <div class="container">
        <br/>
        <h2>Changing profile:</h2>
        {% load crispy_forms_tags %}

        <form class="searchform" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br/>
            <input type="submit" class="btn btn-lg btn-block btn-primary">
        </form>
    </div>
  
{% endblock %}

main/templates/main/by_category.html
{% extends "main/base.html" %}
{% block content %}

    <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
             {% if person %}
                {% for person in person %}
              
                {% if forloop.first %}
                <h2>{{ person.rubric }} category profiles:</h2>
                <hr/>
                {% endif %}
              
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow">
                    <div class="card-body">
                      <h2 class="card-text"><a href="{% url 'main:profile' aid=person.pk %}">{{ person.user.username }}</a></h2>    
                      <h3 class="card-text">About: {{ person.biography }}</h3>
                      <h3 class="card-text">Dream: {{ person.dream }}</h3>
                    </div>
                  </div>
                </div>
                {% endfor %}
              {% else %}
              <h2>There are no profiles with this category.</h2>
              {% endif %}
              
          </div>
        </div>
    </div>
    
{% endblock content %}

main/templates/main/create.html
{% extends "main/base.html" %}
{% block content %}
    
    
    <!-- ADD -->
    <div class="container">
        <br/>
        <h2>Add article</h2>
        {% load crispy_forms_tags %}

        <form class="searchform" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br/>
            <input type="submit" class="btn btn-lg btn-block btn-primary" value="Send">
        </form>
    </div>
    
    
    <!-- FOOTER -->
    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
            <a href="#"></a>
            </p>
            <p>All rights reserved by &copy; ComeTrue, 2021</p>
        </div>
    </footer>

{% endblock %}

main/templates/main/delete.html
<!DOCTYPE html>

<html>
<head>
<title>Dreamer</title>    
</head>
<body>
    <h2>Удаление публикации</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Удалить">
    </form>
</body>
</html>

main/templates/main/detail.html
{% extends "main/base.html" %}
{% block content %}
{% load thumbnail %}

<!-- DETAIL -->
<div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
                
                  <div class="card mb-4 box-shadow">

                    {% if blog.image %}
                    <img class="card-img-top" src="{% thumbnail blog.image 'default' %}">
                    {% endif %}

                    <div class="card-body">
                      <h4 class="card-text"><a class="p-q text-muted" href="{% url 'main:profile' aid=blog.authorid %}">{{ blog.author }}</a></h4>
                      <h3 class="card-text"><a href="{% url 'main:detail' blog_id=blog.id %}">{{ blog.title }}</a></h3>
                      {% if blog.text %}
                      <hr>
                      <p class="card-text">{{ blog.text }}</p>
                      {% endif %}
                      <hr>
                      <p class="card-text">{{ blog.views }} - Views</p>
                        
                      
                        
                      <h2>
                      {% if request.user.username == blog.author or request.user.is_staff %}
                        <button type="button" class="btn btn-lg btn-block btn-primary" href="{% url 'main:delete' blog_id=blog.pk %}">Delete</button>
                      {% endif %}

                      {% if request.user.username != blog.author and blog.authorid not in request.user.person.subscribed %}
                        <button type="button" class="btn btn-lg btn-block btn-primary" href="{% url 'main:subscribe' author_id=blog.authorid %}">Subscribe</button>
                      {% endif %}

                      {% if request.user.username != blog.author and blog.authorid in request.user.person.subscribed %}
                        <button type="button" class="btn btn-lg btn-block btn-primary" href="{% url 'main:unsubscribe' author_id=blog.authorid %}">Unsubscribe</button>
                      {% endif %}
                      </h2>
                        
                    </div>
                    
                  </div>
                
          </div>
        </div>
      </div>
    
    
    
    
    <!-- COMMENTS -->
    
    
    <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            {% if comment %}
            <h1 class="cover-heading">Comments</h1>
            {% endif %}
            <div class="col-md-4">
            {% for comment in comment %}
    
                  <div class="card mb-4 box-shadow">

                    <div class="card-body">
                      <h4 class="card-text"><a class="p-q text-muted" href="{% url 'main:profile' aid=blog.authorid %}">{{ comment.comment_author }}</a></h4>
                      <p class="card-text">{{ comment.comment_text }}</p>
                      <hr>
                      <p class="card-text">{{ comment.comment_published }} - Views</p>
                        
                      {% if request.user.username == comment.comment_author or request.user.is_staff %}
                      <div class="btn-group">
                      <h3>
                      <a class="btn btn-sm btn-outline-secondary" href="{% url 'main:comment_delete' blog_id=blog.pk comment_id=comment.pk %}">Delete Comment</a>
                      </h3>
                      {% endif %}
                      </div>
                    </div>
                      
                </div>
            {% endfor %} 
            
            <h2 class="cover-heading">Add comment</h2>
            {% load crispy_forms_tags %}
            <form action=""method = "post">
            {% csrf_token %}
            {{ form|crispy }}
            <br/>
            <input type="submit" class="btn btn-lg btn-block btn-primary" value="Send">
            </form>
            
          </div>
          </div>
        </div>
      </div>
    
{% endblock %}

main/templates/main/dreamerindex.html
//INDEX DREAMER

<!DOCTYPE html>

{% load thumbnail %}
{% load static %}

<html>
<head>
<title>Dreamer v1.2</title>
<meta charset="UTF-8">
<link rel="stylesheet" href="{% static 'css/indexcss.css' %}">

</head>
    
<body>
    <div class="header">
    <h2><img src="{% static 'logo/logo.png' %}" height="100" width="100" class="logo"><a href="{% url 'main:profile' aid=request.user.id %}">
    {% if request.user.is_authenticated %} Привет,{{request.user.username}}!</a>{% endif %}
    {% if not request.user.is_authenticated %}<a class="headertext" href="{% url 'main:register' %}" >Зарегистрироваться</a> <a class="headertext" href="{% url 'main:login' %}" >Войти</a>{% endif %} {% if request.user.is_authenticated %}<a class="headertext" href="{% url 'main:logout' %}" >Выйти</a>{% endif %} <a class="headertext" href="{% url 'main:homepage' %}" >Главная</a> <a class="headertext" href="{% url 'main:my_subscribes' %}">Мои подписки</a> <a href="{% url 'main:profile' aid=request.user.id %}"></a> <a class="headertext" href="{% url 'main:profile' aid=request.user.id %}">Мой Профиль</a> <a class="headertext" href="{% url 'main:searchinput' %}">Поиск</a></h2>
    </div>
    
    <div class="category">
    <h2>Категории: {% for rubric in rubrics %} {% if forloop.last %} <a href="{% url 'main:by_category' category=rubric.drubric %}">{{ rubric.drubric }}</a>. {% else %} <a href="{% url 'main:by_category' category=rubric.drubric %}">{{ rubric.drubric }}</a>, {% endif %} {% endfor %}</h2>
    </div>
    
    
    {% for best_person in best_person %}
    {% if best_person.id != request.user.id %}
        <div class="person"> 
        <h2><a href="{% url 'main:profile' aid=best_person.pk %}">{{ best_person.user.username }}</a></h2>
        <h3>О себе: {{ best_person.biography }} </h3>
        <h3>Мечта: {{ best_person.dream }} </h3>
        </div>
    {% endif %}
    {% endfor %}
    
    {% for person in person %}
    {% if person.id != request.user.id %}
        <div class="person"> 
        <h2><a href="{% url 'main:profile' aid=person.pk %}">{{ person.user.username }}</a></h2>
        <h3>О себе: {{ person.biography }} </h3>
        <h3>Мечта: {{ person.dream }} </h3>
        </div>
    {% endif %}
    {% endfor %}
</body>
</html>

main/templates/main/my_tasks.html
<!DOCTYPE html>

<html>
<head>
<title>Dreamer</title>    
</head>
<body>
    {% if request.user.is_authenticated %}
    <h2>Привет, {{request.user.username}}!</h2>
    {% endif %}
    <h2><a href="{% url 'main:register' %}" >Зарегистрироваться</a> <a href="{% url 'main:login' %}" >Войти</a> <a href="{% url 'main:logout' %}" >Выйти</a> <a href="{% url 'main:index' %}" >Главная</a> <a href="{% url 'main:my_subscribes' %}">Мои подписки</a> <a href="{% url 'main:profile' aid=request.user.id %}"> <a href="{% url 'main:profile' aid=request.user.id %}">Мой Профиль</a></a></h2>
    {% for blog in blog %}
        <div>
            {% if request.user.username == blog.author %}
            <h2>{{ blog.author }}</h2>
            <h2><a href="{% url 'main:detail' blog_id=blog.pk %}">{{ blog.title }}</a></h2>
            <h3>{{ blog.text }}</h3>
            {% endif %}
        </div>
    {% endfor %}
</body>
</html>

main/templates/main/personsearch.html
{% extends "main/base.html" %}
{% block content %}

    <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
             {% if persons %}
                {% for person in persons %}
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow">
                    <div class="card-body">
                      <h2 class="card-text"><a href="{% url 'main:profile' aid=person.pk %}">{{ person.username }}</a></h2>    
                      <h3 class="card-text">About: {{ person.person.biography }}</h3>
                      <h3 class="card-text">Dream: {{ person.person.dream }}</h3>
                    </div>
                  </div>
                </div>
                {% endfor %}
              {% else %}
              <h2>The search has not given any results.<a href="{% url 'main:searchinput' %}">Return to search.</a></h2>
              {% endif %}
              
          </div>
        </div>
    </div>

{% endblock %}